//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_1_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ORDER
    {
        public int ID_CUSTOMER_ORDER { get; set; }
        public int NAME_COFFEE_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public int ORDER_COFFEE_ID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual CLIENT CLIENT1 { get; set; }
        public virtual NAME_COFFEE NAME_COFFEE { get; set; }
        public virtual ORDER_COFFEE ORDER_COFFEE { get; set; }
        public virtual NAME_COFFEE NAME_COFFEE1 { get; set; }
        public virtual ORDER_COFFEE ORDER_COFFEE1 { get; set; }
    }
}
