//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_1_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAME_COFFEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAME_COFFEE()
        {
            this.CUSTOMER_ORDER = new HashSet<CUSTOMER_ORDER>();
            this.CUSTOMER_ORDER1 = new HashSet<CUSTOMER_ORDER>();
        }
    
        public int ID_NAME_COFFEE_HOUSE { get; set; }
        public string TITLE { get; set; }
        public string ADDRESS_COFFEE_HOUSE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER> CUSTOMER_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ORDER> CUSTOMER_ORDER1 { get; set; }
    }
}
